spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:~/emr;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        format_sql: true
        type:
          descriptor:
            sql: trace
    generate-ddl: true
    # data.sql 초기 데이터 생성 전 ddl 생성
    defer-datasource-initialization: true

  # data.sql 초기 데이터 생성
  sql:
    init:
      mode: always
